# Generated by Django 3.2.6 on 2021-08-17 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('message', models.TextField(max_length=400, verbose_name='Descrição')),
                ('conclusion_at', models.DateTimeField(blank=True)),
                ('concluded', models.BooleanField(default=False, verbose_name='Concluído')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
