# Generated by Django 3.2.6 on 2021-08-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
