# Generated by Django 3.2.6 on 2021-08-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_conclusion_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrição'),
        ),
    ]
