# Generated by Django 3.2.6 on 2021-08-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='message',
        ),
    ]
